{{- if and .Values.subscription.enabled .Values.ingress.enabled -}}
{{- $className := default .Values.ingress.className .Values.subscription.ingress.className -}}
{{- $annotations := default .Values.ingress.annotations .Values.subscription.ingress.annotations -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "remnawave-panel.fullname" . }}-subscription
  labels:
    {{- include "remnawave-panel.labels" . | nindent 4 }}
  {{- with $annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if $className }}
  ingressClassName: {{ $className }}
  {{- end }}
  {{- with .Values.subscription.ingress.tls }}
  tls:
    {{- range . }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.subscription.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "remnawave-panel.fullname" $ }}
                port:
                  name: subscription
          {{- end }}
    {{- end }}
{{- end }}
